import re
import pandas as pd


class Helper:
    # Constants
    FILE_NAMES = ['./DB/LyricsFirstPeriod.csv', './DB/LyricsSecondPeriod.csv']
    period_Analysis_Filenames = ['./results/song_analysis_first_period.csv',
                                 './results/song_analysis_second_period.csv']

    My_CURSE_WORDS = {'fuck', 'shit', 'bitch', 'ass', 'damn', 'bastard', 'hell', 'dick', 'piss', 'crap', 'prick',
                      'cock',
                      'pussy', 'slut', 'douche', 'cunt', 'motherfucker', 'fucking', 'ballsack', 'nuts', 'pussy', 'gay',
                      'fat', 'shot', 'gun', 'shoot', 'Glock', 'puke', 'faggot', 'bullets', 'murderin', 'roaches',
                      'midgets',
                      'retard', 'retarded', 'suck', 'vomit', 'suck', 'groin', 'alcohol', 'alcoholic', 'hit',
                      'influence',
                      'fat', 'motherfuckin', 'stealing', 'stealin', 'smoke', 'knives', 'killin', 'killing', 'screw',
                      'ass',
                      'kicked', 'drugs', 'drug'}
    Slang = {'murderin', 'servin', 'mcs', 'tryin', 'brainiac', 'relaxin', 'motherfuckin', 'rhymin', 'slimin',
             'starin', 'gamblin', 'goin', 'steppin', 'slammin', 'droppin', 'stealin', 'usin', 'nigga',
             'niggas', 'jackin', 'knives', 'steamin', 'slicin', 'killin', 'gangsta', 'cancelin',
             'plannin', 'makin', 'ownin'}
    MyNames = {'shady', 'eminem', '2pac', 'biggie', 'kim', 'hailie', 'dre', 'kim', 'kendrick', 'santa claus',
               'jimmy carter', 'jerry springer', 'hilary clinton', 'nicole', 'norman bates', 'susan', 'dave', 'john',
               'kelly', 'ron', 'sue', 'marshall', 'mike tyson', 'pete', 'ron goldman', 'sarty schottenheimer',
               'outsidaz', 'jenny craig', 'slim shady', 'slim', 'momma', 'mom', 'Stan', 'ronnie', 'bonnie',
               'Eric', 'Rémy Martin', 'mathers', 'proof', 'ludacris', 'Marilyn Manson', 'michael jackson', 'reggie',
               'kim mathers', 'bobby', 'r. kelly', 'fetty wap', 'bizarre', 'tara reid', 'richard ramirez', 'jay',
               'elvis',
               'jack the ripper', 'jay-z', 'nas', 'paul', 'bin Laden', 'mama', 'diddy', 'billie eilish', 'stevie',
               'nate'}

    NamesDataSet = {"Gorillaz", "Red Hot Chili Peppers", "50 Cent", "Metallica", "Coldplay", "Daft Punk", "Linkin Park",
                    "Radiohead", "AC/DC", "Black Eyed Peas", "Michael Jackson", "P!nk", "Eminem", "Pharrell Williams",
                    "Khalid", "Shakira", "Machine Gun Kelly", "Nicky Jam", "The Beatles", "Pitbull", "Sean Paul",
                    "Elvis Presley", "2Pac", "Snoop Dogg", "Lil Wayne", "Sia", "Fleetwood Mac", "ABBA", "Frank Sinatra",
                    "TiÃ«sto", "Elton John", "JAY-Z", "21 Savage", "Kanye West", "Luis Miguel", "BeyoncÃ©",
                    "Daddy Yankee", "Don Toliver", "Camilo", "Britney Spears", "Farruko", "Wisin & Yandel", "Disney",
                    "Chris Brown", "Tory Lanez", "Mariah Carey", "A.R. Rahman", "Die drei ???", "Pritam",
                    "Shreya Ghoshal", "Pink Floyd", "System Of A Down", "Green Day", "Ludovico Einaudi", "Muse",
                    "Aerosmith", "Slipknot", "Oasis", "The Rolling Stones", "Hans Zimmer", "Deftones", "blink-182",
                    "Bob Marley & The Wailers", "David Bowie", "Bon Jovi", "Dr. Dre", "Creedence Clearwater Revival",
                    "U2", "Nate Dogg", "Juanes", "ManÃ¡", "Bee Gees", "Billy Joel", "The Notorious B.I.G.",
                    "Enrique Iglesias", "Timbaland", "Alejandro Sanz", "Whitney Houston", "Madonna", "Alicia Keys",
                    "John Mayer", "Christina Aguilera", "Marc Anthony", "Ricardo Arjona", "Stevie Wonder", "Ludacris",
                    "Plan B", "Aventura", "Usher", "Vicente FernÃ¡ndez", "Alejandro FernÃ¡ndez", "T-Pain",
                    "Johann Sebastian Bach", "JhenÃ© Aiko", "Alka Yagnik", "Udit Narayan", "Vishal-Shekhar",
                    "Bibi und Tina", "Yuvan Shankar Raja", "Bibi Blocksberg", "Pearl Jam", "The Offspring",
                    "Johnny Cash", "Eagles", "Korn", "MGMT", "MF DOOM", "The Cure", "Jack Johnson", "Outkast",
                    "Ice Cube", "Phil Collins", "John Williams", "Soda Stereo", "Nas", "Luis Fonsi", "Backstreet Boys",
                    "Los Ãngeles Azules", "Zedd", "Nat King Cole", "Armin van Buuren", "Juicy J", "Julieta Venegas",
                    "Bruce Springsteen", "Wham!", "JosÃ© JosÃ©", "Los Tigres Del Norte", "Bryan Adams", "Dean Martin",
                    "Nelly Furtado", "Ricky Martin", "Jennifer Lopez", "Sido", "Wolfgang Amadeus Mozart",
                    "Juan Gabriel", "Nelly", "FrÃ©dÃ©ric Chopin", "Marco Antonio SolÃ­s", "CÃ©line Dion", "Alesso",
                    "Joan Sebastian", "Bing Crosby", "S. P. Balasubrahmanyam", "Sonu Nigam", "Lata Mangeshkar",
                    "La Arrolladora Banda El LimÃ³n De Rene Camacho", "KK", "AnahÃ­", "Shankar Mahadevan", "Kumar Sanu",
                    "Iron Maiden", "Black Sabbath", "thasup", "Limp Bizkit", "John Lennon", "Disturbed", "The Doors",
                    "R.E.M.", "Scorpions", "Norah Jones", "The Smashing Pumpkins", "Skillet", "Earth, Wind & Fire",
                    "Weezer", "Sabaton", "Train", "Rod Stewart", "Tears For Fears", "TOTO", "Shaggy",
                    "Charlie Brown Jr.", "La Oreja de Van Gogh", "London Symphony Orchestra", "Marvin Gaye",
                    "George Michael", "Gwen Stefani", "The Game", "The Beach Boys", "Journey", "Dolly Parton",
                    "Gabry Ponte", "SCH", "Ludwig van Beethoven", "Jay Chou", "Diddy", "Baby Rasta", "Shania Twain",
                    "Hillsong Worship", "George Strait", "Berliner Philharmoniker", "Rahat Fateh Ali Khan",
                    "Kishore Kumar", "Shekhar Ravjiani", "Los Tucanes De Tijuana", "Intocable", "Los Temerarios",
                    "K. S. Chithra", "TKKG", "Sunidhi Chauhan", "Benjamin BlÃ¼mchen", "Rage Against The Machine",
                    "The White Stripes", "Lynyrd Skynyrd", "Dido", "Eric Clapton", "Bob Dylan", "Bill Withers",
                    "Louis Armstrong", "Enya", "Papa Roach", "Ozzy Osbourne", "a-ha", "MÃ¶tley CrÃ¼e",
                    "Alice In Chains", "Ella Fitzgerald", "Sade", "Wyclef Jean", "Antonio Vivaldi", "Simon & Garfunkel",
                    "Robbie Williams", "Patrick Watson", "Busta Rhymes", "Paul McCartney", "Los Enanitos Verdes",
                    "Hombres G", "Sufjan Stevens", "Prince", "Boney M.", "Willie Nelson", "Van Morrison",
                    "Ms. Lauryn Hill", "Lil Jon", "Chayanne", "Alan Jackson", "Destiny's Child", "Bronco",
                    "Ana Gabriel", "Brenda Lee", "Ashanti", "Andy Williams", "JesÃºs AdriÃ¡n Romero", "Bruno & Marrone",
                    "Method Man", "Sezen Aksu", "G. V. Prakash", "Banda El Recodo", "Devi Sri Prasad", "Hariharan",
                    "Karthik", "Harris Jayaraj", "3 Doors Down", "The Black Keys", "Marilyn Manson", "Santana",
                    "Electric Light Orchestra", "Jimi Hendrix", "Sum 41", "Coolio", "Megadeth", "The Clash",
                    "Otis Redding", "Sting", "Dimitri Vegas & Like Mike", "Gustavo Cerati", "DMX", "Tech N9ne",
                    "The Jackson 5", "Aretha Franklin", "Cyndi Lauper", "AndrÃ©s Calamaro", "Mary J. Blige",
                    "Andrea Bocelli", "Lionel Richie", "JosÃ© Feliciano", "Duster", "Sin Bandera",
                    "Pyotr Ilyich Tchaikovsky", "Hillsong UNITED", "Laura Pausini", "Westlife", "Kylie Minogue",
                    "Missy Elliott", "Cristian Castro", "Claude Debussy", "Roberto Carlos", "Hikaru Utada",
                    "Tim McGraw", "The Alchemist", "Kenny Chesney", "Pepe Aguilar", "Thalia", "RocÃ­o DÃºrcal",
                    "Selena", "R. D. Burman", "Guru Randhawa", "Conjunto Primavera", "Jenni Rivera", "Javed Ali",
                    "Amaal Mallik", "Chinmayi", "Years & Years", "Lenny Kravitz", "Moby", "Queens of the Stone Age",
                    "Blur", "Yusuf / Cat Stevens", "Gustavo Santaolalla", "Pantera", "Tracy Chapman", "Kidz Bop Kids",
                    "Blondie", "Bunbury", "John Denver", "E-40", "Julio Iglesias", "Willie ColÃ³n", "BabasÃ³nicos",
                    "Caifanes", "Grupo Niche", "Kenny Rogers", "Miguel BosÃ©", "Eros Ramazzotti", "Ã‘ejo",
                    "Franco De Vita", "Olivia Newton-John", "Carpenters", "Leo Dan", "Project Pat",
                    "Royal Philharmonic Orchestra", "Fergie", "Ja Rule", "PÃ©ricles", "Gilberto Santa Rosa",
                    "Jamie Foxx", "Ricardo Montaner", "Ciara", "Raekwon", "L.V.", "Rascal Flatts", "ValentÃ­n Elizalde",
                    "Asha Bhosle", "Antonio Aguilar", "Los Cadetes De Linares", "Madlib", "Chalino Sanchez",
                    "Grupo Bryndis", "Los Invasores De Nuevo LeÃ³n", "S. Janaki", "K. J. Yesudas", "Shankar-Ehsaan-Loy",
                    "The Mamas & The Papas", "Genesis", "Cypress Hill", "Wu-Tang Clan", "The Who", "CafÃ© Tacvba",
                    "Incubus", "Gigi D'Agostino", "Eurythmics", "MÃ¤go de Oz", "Snow Patrol", "Chuck Berry",
                    "Nina Simone", "Bob Sinclar", "Joe Hisaishi", "Counting Crows", "Sam Cooke", "UB40", "Duran Duran",
                    "Etta James", "Tom Petty", "Los AutÃ©nticos Decadentes", "The Doobie Brothers", "Yo-Yo Ma",
                    "Air Supply", "Paul Simon", "Tina Turner", "Bootsy Collins", "Spice Girls", "Neil Diamond",
                    "*NSYNC", "JoaquÃ­n Sabina", "INNA", "Kenny Loggins", "James Taylor", "Cher", "TLC",
                    "Grupo RevelaÃ§Ã£o", "Wiener Philharmoniker", "Toby Keith", "Herbert von Karajan", "Emmanuel",
                    "Perry Como", "Mohammed Rafi", "Ol' Dirty Bastard", "Sukhwinder Singh", "Burl Ives",
                    "FÃ¼nf Freunde", "Shaan", "Sadhana Sargam", "Ray Charles", "Deep Purple", "Judas Priest",
                    "No Doubt", "Jarabe De Palo", "Kool & The Gang", "Erik Satie", "Mobb Deep", "Creed",
                    "Los Fabulosos Cadillacs", "TheFatRat", "A Tribe Called Quest", "Hardwell", "Erykah Badu",
                    "Don Diablo", "Pet Shop Boys", "Modern Talking", "Godsmack", "George Harrison", "Caetano Veloso",
                    "Skank", "Waylon Jennings", "Tony Bennett", "Steely Dan", "Fat Joe", "Aaliyah", "Riton",
                    "Eason Chan", "Keyshia Cole", "Johannes Brahms", "Academy of St. Martin in the Fields",
                    "Paulina Rubio", "Ghostface Killah", "Tom Petty and the Heartbreakers", "Yo Gotti", "Pradeep Kumar",
                    "Eve", "Marisela", "Alejandra Guzman", "ZezÃ© Di Camargo & Luciano", "Mijares", "Silambarasan TR",
                    "Sujatha", "R. Kelly", "Los Inquietos Del Norte", "Anuradha Paudwal", "Abhijeet", "Sheila On 7",
                    "Kavita Krishnamurthy", "Jatin-Lalit", "Jamiroquai", "El Cuarteto De Nos", "Placebo", "Tom Morello",
                    "Nine Inch Nails", "Patricio Rey y sus Redonditos de Ricota", "Will Smith", "PXNDX",
                    "Heroes Del Silencio", "Bonnie Tyler", "Sir Simon Rattle", "Boyz II Men", "AntÃ´nio Carlos Jobim",
                    "Boston", "Kid Rock", "The All-American Rejects", "Dybbukk", "Kansas", "Mecano", "The Temptations",
                    "Heart", "Prezioso", "Sheryl Crow", "Bone Thugs-N-Harmony", "Matchbox Twenty", "kevoxx",
                    "Eddie Santiago", "Diana Ross", "Xzibit", "Howard Shore", "Fabolous", "Arizona Zervas", "Tarkan",
                    "Darius Rucker", "MÃ¼slÃ¼m GÃ¼rses", "Frankie Ruiz", "Ivete Sangalo", "The Wiggles", "The Chicks",
                    "Yuri", "Mika Singh", "Binomio de Oro de AmÃ©rica", "Dwele", "Himesh Reshammiya", "Chris Tomlin",
                    "Pancho Barraza", "George Frideric Handel", "Pesado", "Traditional",
                    "Grupo Laberinto", "Ennio Morricone", "Seu Jorge", "Leonard Cohen", "Fugees", "Good Charlotte",
                    "MotÃ¶rhead", "Nightwish", "Jorge Drexler", "Grateful Dead", "Eazy-E", "Roy Orbison",
                    "Stevie Nicks", "The Cramps", "Daniel Hope", "Crowded House", "Sir Neville Marriner",
                    "Sir Arthur Conan Doyle", "In Flames", "Scooter", "Gloria Estefan", "Richard Marx", "Djavan",
                    "DJ Premier", "Chris Rea", "D12", "Los Palmeras", "Ginuwine", "RaÃ§a Negra", "JosÃ© Luis Perales",
                    "Janet Jackson", "Twista", "Alonzo", "Teoman", "Jerry Rivera", "Too $hort", "La Sonora Dinamita",
                    "Robert Schumann", "James Horner", "ChitÃ£ozinho & XororÃ³", "Playero", "JosÃ© Alfredo Jimenez",
                    "Camille Saint-SaÃ«ns", "Tammi Terrell", "Ati242", "Los Angeles De Charly",
                    "Los Dareyes De La Sierra", "Los Acosta", "Inspectah Deck", "Naresh Iyer", "Roop Kumar Rathod",
                    "Gipsy Kings", "John Coltrane", "Iggy Pop", "Barry White", "Phoenix", "Thousand Foot Krutch",
                    "Beck", "Jim Croce", "Bonobo", "Billie Holiday", "Smash Mouth", "Al Green", "Joe Cocker",
                    "The Outfield", "La Mosca Tse-Tse", "Men At Work", "Kenny Dope", "mor ve Ã¶tesi", "Celia Cruz",
                    "Charly GarcÃ­a", "Craig David", "Fito Paez", "John Mellencamp", "Elvis Crespo", "Lil' Kim",
                    "TobyMac", "Zeca Pagodinho", "Jadakiss", "London Philharmonic Orchestra", "RZA", "Brad Paisley",
                    "Hank Williams, Jr.", "JÃ³hann JÃ³hannsson", "112", "Nusrat Fateh Ali Khan", "Brandy",
                    "Leo Mattioli", "Marisa Monte", "Udo Lindenberg", "Mandy Moore", "Santiago Ziesmer", "Belo",
                    "Outlawz", "Dewa 19", "Mase", "Banda Cuisillos", "Leon James", "Los Yonic's",
                    "Banda PequeÃ±os Musical", "Ilaiyaraaja", "Joy Division", "J.J. Cale", "Gojira", "Commodores",
                    "Chet Baker", "Mos Def", "Modest Mouse", "Lamb of God", "Death Cab for Cutie", "Billy Ray Cyrus",
                    "Los Panchos", "CeeLo Green", "Dusty Springfield", "Pretenders", "Elliott Smith", "Peter Gabriel",
                    "Insane Clown Posse", "REO Speedwagon", "Europe", "Whitesnake", "Gilberto Gil", "Vasco Rossi",
                    "HÃ©ctor Lavoe", "Kingpin Skinny Pimp", "Silvio RodrÃ­guez", "AndrÃ©s Cepeda", "Franz Schubert",
                    "La Ley", "Barbra Streisand", "Donna Summer", "Edvard Grieg", "Diego Torres", "ZÃ© Ramalho",
                    "Luciano Pereyra", "Faith Evans", "Lulu Santos", "Shakin' Stevens", "Jota Quest",
                    "VÃ­ctor Manuelle", "Javier SolÃ­s", "Vedo", "Exaltasamba", "Faith Hill", "Mr.Children", "Redman",
                    "Los Rehenes", "LX", "Joe", "Ebru GÃ¼ndeÅŸ", "Vijay Yesudas", "The Velvet Underground",
                    "The Cinematic Orchestra", "Cultura ProfÃ©tica", "Staind", "Grover Washington, Jr.", "Stan Getz",
                    "Dave Matthews Band", "Alphaville", "Lifehouse", "BUMP OF CHICKEN", "Martin Solveig",
                    "El Canto Del Loco", "Alice Cooper", "Meat Loaf", "Savage Garden", "ATB", "Alexandre Desplat",
                    "Kris Kristofferson", "Gavin Greenaway", "Lisa Gerrard", "Danny Elfman", "Los Pericos",
                    "George Benson", "Kenny G", "Carly Simon", "BÃ¶hse Onkelz", "Stephen Cleobury", "DENNIS",
                    "Antonio Orozco", "Three 6 Mafia", "Sergei Rachmaninoff", "Engenheiros Do Hawaii",
                    "Luther Vandross", "Cocteau Twins", "Laxmikantâ€“Pyarelal", "Mark Morrison", "Randy Travis",
                    "Daniel Barenboim", "Travis Tritt", "Lilly Goodman", "Marcos Witt", "Niro", "Mi Banda El Mexicano",
                    "ARASHI", "Banda Machos", "Salimâ€“Sulaiman", "Harish Raghavendra", "Glenn Fredly", "Sertab Erener",
                    "Ramon Ayala Y Sus Bravos Del Norte", "Ace of Base", "Tom Jones", "Michael Bolton", "James Brown",
                    "JoÃ£o Gilberto", "Soft Cell", "KC & The Sunshine Band", "Jorge Ben Jor", "Blue Ã–yster Cult",
                    "BjÃ¶rk", "Don McLean", "Gloria Gaynor", "Blackstreet", "Claudio Abbado", "Charles Aznavour",
                    "Os Paralamas Do Sucesso", "Vilma Palma e Vampiros", "MÅ“nia", "Thomas Newman", "Luciano Pavarotti",
                    "Alceu ValenÃ§a", "Third Eye Blind", "John Powell", "Armand Van Helden", "Rafaga", "Don Henley",
                    "D.O.D", "Toni Braxton", "Warren G", "Capital Inicial", "Kalash", "Marta SÃ¡nchez",
                    "La Sonora Santanera", "Grupo 5", "Kendo Kaponi", "Shenseea", "Diomedes Diaz", "Bombay Jayashri",
                    "Gene Autry", "Divya Kumar", "Dino James", "Grupo Yndio", "Rionegro & SolimÃµes", "Mano",
                    "Leonardo", "Saindhavi", "Swarnalatha", "Roger", "Ananya Bhat", "Serdar OrtaÃ§", "Janis Joplin",
                    "Fatboy Slim", "Cream", "Dropkick Murphys", "Stevie Ray Vaughan", "Eiffel 65", "Take That",
                    "Mindless Self Indulgence", "Thin Lizzy", "Jovanotti", "Four Tops", "Julio Jaramillo", "Los Cafres",
                    "RubÃ©n Blades", "Vengaboys", "Killswitch Engage", "Christopher Cross", "James Newton Howard",
                    "Die Ã„rzte", "Poison", "Franz Liszt", "Soprano", "Sarah McLachlan", "Allman Brothers Band",
                    "El Barrio", "Natalie Cole", "Ronan Keating", "Jackson Browne", "Kelis", "Fiona Apple",
                    "CÃ¡ssia Eller", "Philharmonia Orchestra", "Kirk Franklin", "Hector & Tito",
                    "The Lyndhurst Orchestra", "The Pointer Sisters", "Gala", "Ying Yang Twins", "Mayday",
                    "The Supremes", "Kool Savas", "Vince Gill", "GZA", "Pezet", "Mahalakshmi Iyer", "M. M. Keeravani",
                    "Harini", "Aline Barros", "Rolf Zuckowski", "South Park Mexican", "Rammstein", "Queen",
                    "Justin Timberlake", "Fall Out Boy", "David Guetta", "Akon", "Don Omar", "Miguel", "TWICE", "Logic",
                    "Nickelback", "RM", "Kelly Clarkson", "Badshah", "Depeche Mode", "The Strokes", "T.I.",
                    "The Police", "Juan Luis Guerra 4.40", "BONES", "Carlos Vives", "Christopher von Uckermann",
                    "Los Bukis", "KISS", "Avenged Sevenfold", "will.i.am", "ZoÃ©", "Daryl Hall & John Oates",
                    "Kate Bush", "Pusha T", "Blake Shelton", "DJ Nelson", "The Cranberries", "Pixies", "Almighty",
                    "Jelly Roll", "Germ", "Manu Chao", "M83", "Rise Against", "INXS", "Travis Barker", "Nile Rodgers",
                    "Roxette", "Annie Lennox", "Oliver Heldens", "Tego CalderÃ³n", "David Bisbal", "Booba",
                    "Gloria Trevi", "Keith Urban", "Xavier Wulf", "Dhanush", "ZZ Top", "TOOL", "Billy Idol", "Natiruts",
                    "Estopa", "Belinda", "Brooks & Dunn", "Cardenales De Nuevo LeÃ³n", "Bobby Helms", "Beastie Boys",
                    "Chicago", "LegiÃ£o Urbana", "Abel Pintos", "Tchakabum", "LP", "LMFAO", "America", "The National",
                    "I Virtuosi Italiani", "Slayer", "Kaskade", "Jimmy Eat World", "Manuel Carrasco",
                    "Banda Los Recoditos", "Ramones", "Rob Zombie", "Benny Benassi", "Stone Temple Pilots", "New Order",
                    "Simple Minds", "Damas Gratis", "Elefante", "Bacilos", "Camilo Sesto", "Youjeen", "Bread", "Mario",
                    "Kelly Rowland", "Eraserheads", "Vijay Prakash", "Damian Marley", "Hoobastank", "PSY",
                    "SEGA SOUND TEAM", "Jimmy Buffett", "Vanesa MartÃ­n", "Jeet Gannguli", "Molotov", "O Rappa",
                    "Fito y Fitipaldis", "The Kinks", "Aphex Twin", "Yiruma", "Tiziano Ferro", "Nando Reis",
                    "Fernandinho", "Ana BÃ¡rbara", "Yoko Ono", "Diego Verdaguer", "Darlene Love", "Ben E. King",
                    "Rick Astley", "Diana Krall", "Los Prisioneros", "Majestic", "Raffi", "Miel San Marcos",
                    "Ajay-Atul", "Ahmet Kaya", "Los Amables Del Norte", "The Kiboomers", "LiberaciÃ³n",
                    "Massive Attack", "Yann Tiersen", "Wings", "Lang Lang", "Joan Jett & the Blackhearts", "Alex Ubago",
                    "Ivy Queen", "La Factoria", "Aleks Syntek", "Cedric Gervais", "Olivia", "Ocean Sounds",
                    "Ocean Waves For Sleep", "Akhil", "Misfits", "Seal", "Huey Lewis & The News", "I Monster",
                    "Sub Focus", "Jeff Beck", "Chevelle", "Vybz Kartel", "Steve Edwards", "Timbiriche", "Alabama",
                    "MilionÃ¡rio & JosÃ© Rico", "Stereophonics", "Nick Cave & The Bad Seeds", "Los Bunkers",
                    "surrenderdorothy", "Cassie", "Yovie & Nuno", "Nirvana", "Maroon 5", "Romeo Santos",
                    "Michael BublÃ©", "Yandel", "Gusttavo Lima", "Grupo Marca Registrada", "Foo Fighters",
                    "My Chemical Romance", "Cartel De Santa", "Rick Ross", "Zion & Lennox", "DJ Khaled",
                    "Megan Thee Stallion", "Yuridia", "Luciano", "Avril Lavigne", "PNAU", "Wisin", "2 Chainz",
                    "Natalia Lafourcade", "B.o.B", "Max Richter", "Jason Mraz", "Afrojack", "Danna Paola",
                    "Mohit Chauhan", "Diljit Dosanjh", "Van Halen", "Sorriso Maroto", "Tulsi Kumar",
                    "The Goo Goo Dolls", "Breaking Benjamin", "Dina Rae", "Duelo", "Sublime", "Miranda!", "Def Leppard",
                    "Haricharan", "Audioslave", "Seether", "Simple Plan",
                    "Dave Stewart", "Tito El Bambino", "Gibbs", "No Te Va Gustar", "Alanis Morissette",
                    "Adolescent's Orquesta", "Duman", "Racionais MC's", "Thirty Seconds To Mars", "Nko", "Summer Cem",
                    "Rekha Bhardwaj", "Ice Nine Kills", "John Travolta", "Pixote", "Los Caminantes", "Meet Bros.",
                    "Yeah Yeah Yeahs", "N.W.A.", "The Cars", "Rush", "Jeremy Soule", "Silvestre Dangond", "Grey",
                    "Los Huracanes del Norte", "Panteon Rococo", "La Quinta Estacion", "Nick Jonas", "Curren$y",
                    "Little Big Town", "Parokya Ni Edgar", "The Prodigy", "Fabri Fibra", "Chris Isaak", "Interpol",
                    "Angel Y Khriz", "Inspector", "Alexis y Fido", "MK", "Boosie Badazz", "Meryl Streep",
                    "HÃ©ctor El Father", "Stone Sour", "Carlos Baute", "Chris Lake", "Descemer Bueno", "Ruger",
                    "Shafqat Amanat Ali", "Simone & Simaria", "Harshdeep Kaur", "Redimi2", "t.A.T.u.",
                    "Plain White T's", "First Aid Kit", "Robin Thicke", "Theory of a Deadman", "Los Caligaris",
                    "Juelz Santana", "Bushido", "RaÃ­ Saia Rodada", "Sergio Vega El Shaka", "Gunna", "Arijit Singh",
                    "Led Zeppelin", "John Legend", "The Killers", "Diplo", "Reik", "Amy Winehouse", "Dire Straits",
                    "Three Days Grace", "Mark Ronson", "Alfonso Herrera", "La K'onga", "YG", "Dulce MarÃ­a",
                    "Vishal Dadlani", "Christian ChÃ¡vez", "Kings of Leon", "Thundercat", "Pentatonix", "Ha*Ash",
                    "Tony Dize", "Zion", "Keane", "Melendi", "Kany GarcÃ­a", "Carrie Underwood", "Evanescence",
                    "Idina Menzel", "Miranda Lambert", "Turma do Pagode", "Shinedown", "Jeezy", "Sleeping At Last",
                    "Talking Heads", "Supertramp", "The Fray", "Soulja Boy", "Dierks Bentley", "Benny Dayal", "Kyla",
                    "Cherish", "Franz Ferdinand", "Gotye", "Christian Rode", "Sagopa Kajmer", "Vince Guaraldi Trio",
                    "Willy William", "Bob Seger", "Simply Red", "Gregory Alan Isakov", "Freshlyground", "Hugh Jackman",
                    "Eduardo Costa", "Aloe Blacc", "Lupe Fiasco", "Tribo da Periferia", "Jay Sean", "Madvillain",
                    "Arcade Fire", "Michael Giacchino", "JJ Lin", "Belanova", "Kailash Kher", "Randy", "Phil Wickham",
                    "Kavita Seth", "Claptone", "JosÃ© GonzÃ¡lez", "Billy Talent", "Aaron Smith", "Lamp", "Vicentico",
                    "Billy Currington", "Casting Crowns", "Nightcrawlers", "Josh Turner", "Daughtry", "Tommee Profitt",
                    "Maelo Ruiz", "The Animals", "Benny Sings", "Eric Prydz", "WWE", "Guns N' Roses", "Ã‘engo Flow",
                    "Young Thug", "Bring Me The Horizon", "Flo Rida", "GuÃ¨", "Gucci Mane", "Wizkid", "RBD",
                    "Maite Perroni", "RAF Camora", "Sachin-Jigar", "Jowell & Randy", "Shilpa Rao", "Maren Morris",
                    "11:11 Music Group", "creamy", "Trey Songz", "Gemitaiz", "James Blunt", "The Pussycat Dolls",
                    "Gurlez Akhtar", "Calle 13", "Ramin Djawadi", "Lady A", "Davido", "Bullet For My Valentine",
                    "Juan MagÃ¡n", "Keri Hilson", "J Alvarez", "Thomas Karallus", "Palak Muchhal", "M.I.A.", "Survivor",
                    "Ratatat", "Sara Bareilles", "Fuego", "Bas", "The Verve", "Mazzy Star", "Cascada", "Lloyd",
                    "Lecrae", "Steve Miller Band", "SDP", "Alex Zurdo", "Marcela Gandara", "Natasha Bedingfield",
                    "Emis Killa", "Starship", "Estelle", "D.O.E.", "Espinoza Paz", "Capo", "Reyli Barba",
                    "Arctic Monkeys", "Rihanna", "ArcÃ¡ngel", "De La Ghetto", "Jul", "Macklemore",
                    "Panic! At The Disco", "Paramore", "Ne-Yo", "Gesaffelstein", "Atif Aslam", "Steve Aoki",
                    "Jason Aldean", "Adam Levine", "1nonly", "Marracash", "Dread Mar I", "RADWIMPS", "Cosculluela",
                    "Zac Brown Band", "Thiaguinho", "Volbeat", "Camila", "Gente De Zona", "A Day To Remember", "Wale",
                    "Gym Class Heroes", "Foreigner", "Fonseca", "Caralisa Monteiro", "deadmau5", "Lorenzo",
                    "The Ronettes", "The Kooks", "Cem Adrian", "Teufelskicker", "Lindsey Stirling", "Westside Gunn",
                    "Kollegah", "Shweta Mohan", "Janelle MonÃ¡e", "Klaas", "Yelawolf", "Far East Movement", "Mc Lipi",
                    "Bootie Brown", "Luvli", "Brandi Carlile", "Vierra", "Ed Sheeran", "Miley Cyrus", "Wiz Khalifa",
                    "Calvin Harris", "Taylor Swift", "Future", "Anirudh Ravichander", "Banda MS de Sergio LizÃ¡rraga",
                    "The Smiths", "French Montana", "Tainy", "Neha Kakkar", "Beach House", "Jonas Brothers",
                    "Luke Bryan", "Amitabh Bhattacharya", "Cage The Elephant", "Jesse & Joy", "Canserbero", "Cuco",
                    "Passenger", "Orelsan", "Jon Z", "Eric Church", "Jay Rock", "All Time Low", "Mithoon", "Taio Cruz",
                    "Cali Y El Dandee", "La Maquinaria NorteÃ±a", "Coez", "Lily Allen", "Freddie Gibbs", "Leona Lewis",
                    "El Komander", "Prashant Katheriya", "Paolo Nutini", "W&W", "Chris Young", "CÃ³digo FN",
                    "Neeraj Shridhar", "Peter Fox", "India Martinez", "Nipsey Hussle", "MIKA", "The Temper Trap",
                    "Maneva", "Helene Fischer", "DJ Drama", "Angus & Julia Stone", "Bear McCreary", "Brooke Ligertwood",
                    "The Wombats", "BIGBANG", "Konshens", "Ramirez", "J. Cole", "J Balvin", "Katy Perry", "OneRepublic",
                    "Tyga", "Jorge & Mateus", "Jason Derulo", "Big Sean", "JuliÃ³n Ãlvarez y su NorteÃ±o Banda",
                    "Chris Stapleton", "Five Finger Death Punch", "Bon Iver", "Meek Mill", "Armaan Malik",
                    "Mother Mother", "benny blanco", "Carlos Rivera", "Gerardo Ortiz", "Pierce The Veil", "Skepta",
                    "TAEYANG", "ONE OK ROCK", "Kacey Musgraves", "Lee Brice", "Crystal Castles", "Owl City",
                    "Motionless In White", "Fabrizio Paterlini", "Sean Kingston", "Lucenzo", "Hamza", "Lykke Li",
                    "Pedro CapÃ³", "Mike Perry", "Money Man", "Colbie Caillat", "Zac Efron", "MarÃ­a JosÃ©", "TAEYEON",
                    "Peter Groeger", "Sherlock Holmes", "Soundgarden", "Flowdan", "DJ Alex", "Girls' Generation",
                    "Sam Smith", "Adele", "Tyler, The Creator", "Lady Gaga", "Drake", "Nicki Minaj", "Selena Gomez",
                    "Frank Ocean", "Ariana Grande", "Tame Impala", "Avicii", "Kid Cudi", "Demi Lovato", "Skrillex",
                    "R3HAB", "Bonez MC", "Bomba EstÃ©reo", "G-Eazy", "Kesha", "Charli XCX", "Major Lazer",
                    "Florence + The Machine", "Thaman S", "Stromae", "The Script", "Ryan Lewis", "Carly Rae Jepsen",
                    "Tazzy", "Mustard", "Amit Trivedi", "Elevation Worship", "Kontra K", "Lin-Manuel Miranda",
                    "Bo Burnham", "RÃœFÃœS DU SOL", "Alan Gomez", "Kizzy", "IU", "White Noise for Babies",
                    "Empire of the Sun", "Hollywood Undead", "Boyce Avenue", "Maldy", "Siddhartha", "Colby O'Donis",
                    "Last Child", "Kimbra", "Gaab", "K.Flay", "City Girls", "James Blake", "Set It Off", "accelerate",
                    "Brantley Gilbert", "Enigma NorteÃ±o", "Afgan", "Jaani", "Imagine Dragons", "Bruno Mars",
                    "Steve Lacy", "Playboi Carti", "Justin Bieber", "Carin Leon", "Twenty One Pilots", "Alok",
                    "Chencho Corleone", "Quavo", "Ty Dolla $ign", "Burna Boy", "Ellie Goulding", "King", "H.E.R.",
                    "Swedish House Mafia", "Filipe Ret", "Die drei !!!", "Chief Keef", "Luan Santana", "Jeremih",
                    "MARINA", "La Santa Grifa", "Kevin Gates", "Cody Johnson", "SDM", "back number", "Mumford & Sons",
                    "Timmy Trumpet", "Yo Yo Honey Singh", "Neeti Mohan", "Mr.Kitty", "Glee Cast", "Bradley Cooper",
                    "Paloma Faith", "Popcaan", "Indila", "Mike Posner", "Clayton & RomÃ¡rio", "BK", "Jory Boy",
                    "Selena Gomez & The Scene", "Two Door Cinema Club", "Phantogram", "Kid Ink", "Nakash Aziz",
                    "Haftbefehl", "Murda", "fun.", "Mikky Ekko", "Maher Zain", "Mac Miller", "Kendrick Lamar", "BTS",
                    "One Direction", "Charlie Puth", "Anitta", "Labrinth", "Offset", "Alfredo Olivas", "Prince Royce",
                    "El Alfa", "Calibre 50", "Ghost", "Pablo AlborÃ¡n", "Julia Michaels", "Mambo Kingz",
                    "Florida Georgia Line", "MC Hariel", "Cults", "WILLOW", "Kenshi Yonezu", "Stormzy", "Young Dolph",
                    "La Adictiva", "El Fantasma", "Macklemore & Ryan Lewis", "Xand AviÃ£o", "Asees Kaur", "Disclosure",
                    "Vintage Culture", "Lord Huron", "Noah Cyrus", "ScHoolboy Q", "Rita Ora", "James Bay", "Jessie J",
                    "Die Kita-FrÃ¶sche", "Ufo361", "Karsten GlÃ¼ck", "Simone Sommerland", "C418", "Foster The People",
                    "Purple Disco Machine", "Carla Morrison", "Christina Perri", "Nanpa BÃ¡sico", "Alex G",
                    "Kevin Roldan", "Fran C", "Andy Grammer", "Shouse", "Rvssian", "MAX", "Ana Mena", "Daya",
                    "Jacquees", "Bethel Music", "LuchÃ¨", "Grimes", "Super Simple Songs", "C-Kan", "Jaden",
                    "Skylar Grey", "Leo Santana", "Shilpi Raj", "Rudimental", "Millonario", "Shashaa Tirupati",
                    "Jay Park", "Brett Eldredge", "Lana Del Rey", "The Weeknd", "Maluma", "Feid", "Anuel AA",
                    "Robin Schulz", "Meghan Trainor", "A$AP Rocky", "Childish Gambino", "Anderson .Paak", "blackbear",
                    "Justin Quiles", "Sabrina Carpenter", "PARTYNEXTDOOR", "Russ", "DJ Snake", "Migos",
                    "Tyler Childers", "Little Mix", "Israel & Rodolffo", "Sid Sriram", "TV Girl", "Darell", "Takeoff",
                    "Troye Sivan", "Tulus", "AJR", "Bastille", "C. Tangana", "Clean Bandit", "Aleman",
                    "Chance the Rapper", "Natti Natasha", "Topic", "Mabel Matiz", "White Noise Baby Sleep",
                    "Mon Laferte", "GIMS", "Lomepal", "MNEK", "A$AP Ferg", "Flume", "Lukas Graham", "Nekfeu", "Birdy",
                    "Lasso", "Gzuz", "Salmo", "Ernia", "Zendaya", "Khruangbin", "Falling In Reverse", "Aimer",
                    "Leslie Odom Jr.", "FLETCHER", "Tom Rosenthal", "Kina", "Iggy Azalea", "JP Cooper", "Brett Young",
                    "RÃ­o Roma", "Santhosh Narayanan", "The Paper Kites", "WALK THE MOON", "Vince Staples",
                    "Ronnie Flex", "Of Monsters and Men", "Boef", "Stephanie Beatriz", "Ankit Tiwari",
                    "The Neighbourhood", "Duki", "Travis Scott", "KAROL G", "Metro Boomin", "Mac DeMarco",
                    "Cigarettes After Sex", "Rema", "The 1975", "Halsey", "Bebe Rexha", "James Arthur", "Lil Durk",
                    "Henrique & Juliano", "Tom Odell", "Mitski", "The Chainsmokers", "Kygo", "5 Seconds of Summer",
                    "Matheus & Kauan", "Glass Animals", "The Lumineers", "Martin Garrix", "Melanie Martinez", "Becky G",
                    "Lorde", "Becky Hill", "Wesley SafadÃ£o", "Kumaar", "Tove Lo", "Zara Larsson", "Piso 21", "AURORA",
                    "Joey Bada$$", "Ray Dalton", "Galantis", "Denzel Curry", "Eyedress", "Ãngela Aguilar",
                    "ZÃ© Neto & Cristiano", "Thomas Rhett", "G Herbo", "Nardo Wick", "Lenin RamÃ­rez", "Novo Amor",
                    "Maes", "Ezhel", "Dadju", "Jon Pardi", "The Living Tombstone", "CRO", "alt-J", "Kodaline", "ODESZA",
                    "Matisse", "MÃ˜", "Earl Sweatshirt", "Pouya", "Mabel", "Miky Woodz", "Lauren Daigle", "BIA",
                    "Rag'n'Bone Man", "Dawid PodsiadÅ‚o", "Blueface", "John Newman", "Rich The Kid", "Tinashe",
                    "Fiersa Besari", "Ozuna", "Oliver Tree", "Sebastian Yatra", "NF", "Alan Walker", "NLE Choppa",
                    "Bryson Tiller", "Tanishk Bagchi", "Hozier", "Lizzo", "Daniel Caesar", "Jay Wheeler", "Lazza",
                    "Alec Benjamin", "Vance Joy", "Imanbek", "DJ Luian", "Dalex", "George Ezra", "Felix Jaehn",
                    "LUDMILLA", "Niska", "Rae Sremmurd", "ILLENIUM", "Dilsinho", "LUCKI", "X Ambassadors",
                    "Madison Beer", "Dove Cameron", "Sam Feldt", "Darshan Raval", "Milky Chance", "Jess Glynne",
                    "Capo Plaza", "Dan + Shay", "Mc Kevin", "Jonita Gandhi", "Jaymes Young", "The Walters",
                    "Beach Weather", "Latto", "Justine Skye", "Tion Wayne", "Miggy Dela Rosa", "Ovi", "Ferrugem",
                    "Rochak Kohli", "Omar Varela", "Sam Hunt", "EXO", "Nikhita Gandhi", "Masego",
                    "Rainbow Kitten Surprise", "KAYTRANADA", "Charles Ans", "Jairo Vera", "SofÃ­a Reyes",
                    "Fifth Harmony", "The Vamps", "XXXTENTACION", "Doja Cat", "Lil Uzi Vert", "SZA", "$uicideboy$",
                    "Morgan Wallen", "Lil Peep", "Shawn Mendes", "Luke Combs", "Sech", "Brent Faiyaz", "Kodak Black",
                    "MarÃ­lia MendonÃ§a", "Kali Uchis", "Chase Atlantic", "League of Legends", "Sfera Ebbasta",
                    "Dean Lewis", "Ninho", "Lenny TavÃ¡rez", "Maiara & Maraisa", "Lost Frequencies", "Anne-Marie",
                    "Swae Lee", "Santa Fe Klan", "Kehlani", "Mc Don Juan", "Gera MX", "beabadoobee", "Sigala",
                    "Brytiago", "Red Velvet", "Kane Brown", "LANY", "Ella Henderson", "Diego & Victor Hugo",
                    "James Hype", "Jax Jones", "Seafret", "ZÃ© Felipe", "Bedoes 2115", "Ghostemane", "Young Nudy",
                    "B Praak", "Neo Beats", "Pinguini Tattici Nucleari", "Saweetie", "Gryffin", "Hailee Steinfeld",
                    "Blxst", "Mc Davi", "Lainey Wilson", "Men I Trust", "Hungria Hip Hop", "Fetty Wap", "Naps",
                    "Kelsea Ballerini", "Night Lovell", "The Score", "Ofenbach", "Smino", "Joyner Lucas",
                    "Chelsea Cutler", "Moira Dela Torre", "Los Gemelos De Sinaloa", "AngÃ¨le", "Loud Luxury",
                    "I Prevail", "DIVINE", "Ricky Montgomery", "Matheus Fernandes", "Vishal Mishra", "Post Malone",
                    "Dua Lipa", "Bad Bunny", "Rauw Alejandro", "Myke Towers", "Marshmello", "BLACKPINK", "Morat",
                    "Eladio Carrion", "A Boogie Wit da Hoodie", "Rels B", "Camila Cabello", "RAYE", "Cardi B",
                    "Jack Harlow", "Freddie Dredd", "Lil Yachty", "Phoebe Bridgers", "SEVENTEEN", "Shiloh Dynasty",
                    "JID", "Danny Ocean", "Orochi", "Jubin Nautiyal", "Damso", "Lauv", "Bryant Myers", "Moneybagg Yo",
                    "6LACK", "Joel Corry", "Dermot Kennedy", "Alessia Cara", "Ruth B.", "PNL", "NAV",
                    "Gabito Ballesteros", "Murilo Huff", "Cavetown", "Jessie Reyez", "Vacations",
                    "OFFICIAL HIGE DANDISM", "Montell Fish", "Jonas Blue", "Gustavo Mioto", "White 2115", "Mc IG",
                    "Jeremy Zucker", "Jimin", "Nio Garcia", "Original Broadway Cast of Hamilton", "SYML",
                    "Leon Bridges", "Tom Grennan", "Louis Tomlinson", "Mrs. GREEN APPLE", "Rashmi Virag", "Lil Tracy",
                    "Cheat Codes", "Toby Fox", "PnB Rock", "SAINt JHN", "Sasha Alex Sloan", "Ashe", "Capital Bra",
                    "Billie Eilish", "Joji", "ROSALÃA", "Central Cee", "Manuel Turizo", "Olivia Rodrigo",
                    "Trippie Redd", "YoungBoy Never Broke Again", "DaBaby", "Christian Nodal", "Conan Gray",
                    "070 Shake", "TINI", "MC Cabelinho", "Grupo Firme", "Sidhu Moose Wala", "Hugo & Guilherme",
                    "Rex Orange County", "Elley DuhÃ©", "Calum Scott", "Shiva", "ZAYN", "Lyanno", "La Joaqui",
                    "Niall Horan", "Dave", "Clairo", "Brray", "Ski Mask The Slump God", "Noriel", "Grupo Arriesgado",
                    "MatuÃª", "NCT DREAM", "Karan Aujla", "NEFFEX", "bbno$", "Dominic Fike", "Aya Nakamura",
                    "Pineapple StormTv", "CKay", "Mau y Ricky", "Young Cister", "Yung Gravy", "Bazzi", "Soolking",
                    "Pablo Chill-E", "NCT 127", "Two Feet", "Jorja Smith", "Bad Omens", "Beret", "James Carter", "JIN",
                    "Ben&Ben", "Marca MP", "Bizarrap", "Harry Styles", "Lil Baby", "MÃ¥neskin", "Stray Kids", "Mora",
                    "Fuerza Regida", "Lewis Capaldi", "Ava Max", "Yeat", "Kim Petras", "Jhayco", "Roddy Ricch",
                    "Tate McRae", "Paulo Londra", "Rod Wave", "XamÃ£", "Ovy On The Drums", "L7NNON", "Aitana",
                    "Sleepy Hallow", "WIU", "Em Beihold", "YSY A", "King Von", "LuÃ­sa Sonza", "Noah Kahan", "keshi",
                    "HARDY", "KHEA", "Key Glock", "D-Block Europe", "Trueno", "Ryan Castro", "Omar Apollo", "NIKI",
                    "WOS", "YNW Melly", "LIT killah", "Aitch", "$NOT", "Cazzu", "Tayc", "Jordan Davis", "6ix9ine",
                    "dazy", "42 Dugg", "Tony Aguirre", "Juice WRLD", "Polo G", "Luis R Conriquez", "The Kid LAROI",
                    "Lil Nas X", "Maria Becerra", "MC Ryan SP", "Natanael Cano", "JVKE", "Lil Tjay", "Summer Walker",
                    "Baby Keem", "Giveon", "Tiago PZK", "Geolier", "Lil Tecca", "PolimÃ¡ Westcoast", "Kevin Kaarl",
                    "Lofi Fruits Music", "Chill Fruits Music", "girl in red", "(G)I-DLE", "Tems", "Connor Price",
                    "Ke Personajes", "Edgardo NuÃ±ez", "iann dior", "Grupo Menos Ã‰ Mais", "Dallass", "Apache 207",
                    "24kGoldn", "Kenia OS", "Mc Poze do Rodo", "ATEEZ", "Coi Leray",
                    "Callejero Fino", "Ajaxx", "j-hope", "Los Dos Carnales", "Teto", "Marcianeke", "Zack Tabudlo",
                    "Junior H", "Zach Bryan", "Pop Smoke", "Peso Pluma", "Cris Mj", "Nicki Nicole",
                    "TOMORROW X TOGETHER", "Guilherme & Benuto", "Fred again..", "AP Dhillon", "Eslabon Armado",
                    "Ã˜neheart", "Kotim", "YOASOBI", "Blessd", "Ado", "Tiakola", "ITZY", "sped up nightcore", "Morad",
                    "UZI", "Gazo", "Vaundy", "Felipe Amorim", "NATTAN", "Gurinder Gill",
                    "Solfeggio Healing Frequencies MT", "Kato", "Lvbel C5", "CoComelon", "Quevedo", "Stephen Sanchez",
                    "Mc Paiva ZS", "MEDUZA", "Standly", "Pailita", "Mainstreet", "Miracle Tones", "Ivan Cornejo",
                    "Fujii Kaze", "Hotel Ugly", "ENHYPEN", "Oscar Maydon", "DVRST", "Nicky Youre", "Tz da Coronel",
                    "d4vd", "Ana Castela", "Kordhell", "Mari Fernandez", "Rosa Linn", "PinkPantheress", "BoyWithUke",
                    "FIFA Sound", "Eden MuÃ±oz", "INTERWORLD", "Silk Sonic", "Rain Fruits Sounds", "JoÃ£o Gomes",
                    "Oruam", "Shubh", "Bailey Zimmerman", "IVE", "Arcane", "Sleepy Penguin", "Stars Music Chile",
                    "AYLIVA", "NewJeans", "Grupo Frontera", "Jung Kook", "LE SSERAFIM", "ThxSoMch", "SICK LEGEND"
                    }

    Curse_words_DataSet = {"asshole", "aeolus", "ahole", "anal", "analprobe", "anilingus", "anus", "areola", "areole",
                           "arian", "aryan", "ass", "assbang", "assbanged", "assbangs", "asses", "assfuck", "assfucker",
                           "assh0le", "asshat", "assho1e", "asshole", "assholes", "assmaster", "assmunch", "asswipe",
                           "asswipes", "azazel", "azz", "b1tch", "babe", "babes", "ballsack", "bang", "banger", "barf",
                           "bastard", "bastards", "bawdy", "beaner", "beardedclam", "beastiality", "beatch", "beater",
                           "beaver", "beer", "beeyotch", "beotch", "biatch", "bigtits", "bimbo", "bitch", "bitched",
                           "bitches", "bitchy", "blowjob", "blowjobs", "bod", "bodily", "boink", "bollock", "bollocks",
                           "bollok", "bone", "boned", "boner", "boners", "bong", "boob", "boobies", "boobs", "booby",
                           "booger", "bookie", "bootee", "bootie", "booty", "booze", "boozer", "boozy", "bosom",
                           "bosomy", "bowel", "bowels", "bra", "brassiere", "breast", "breasts", "bugger", "bukkake",
                           "bullshit", "bullshits", "bullshitted", "bullturds", "bung", "busty", "butt", "buttfuck",
                           "buttfucker", "buttfucker", "buttplug", "c.0.c.k", "c.o.c.k.", "c.u.n.t", "c0ck", "c-0-c-k",
                           "caca", "cahone", "cameltoe", "carpetmuncher", "cawk", "cervix", "chinc", "chincs", "chink",
                           "chink", "chode", "chodes", "cl1t", "climax", "clit", "clitoris", "clitorus", "clits",
                           "clitty", "cocain", "cocaine", "cock", "c-o-c-k", "cockblock", "cockholster", "cockknocker",
                           "cocks", "cocksmoker", "cocksucker", "coital", "commie", "condom", "coon", "coons",
                           "corksucker", "crabs", "crack", "cracker", "crackwhore", "crap", "crappy", "cum", "cummin",
                           "cumming", "cumshot", "cumshots", "cumslut", "cumstain", "cunilingus", "cunnilingus",
                           "cunny", "cunt", "cunt", "c-u-n-t", "cuntface", "cunthunter", "cuntlick", "cuntlicker",
                           "cunts", "d0ng", "d0uch3", "d0uche", "d1ck", "d1ld0", "d1ldo", "dago", "dagos", "dammit",
                           "damn", "damned", "damnit", "dawgie-style", "dick", "dickbag", "dickdipper", "dickface",
                           "dickflipper", "dickhead", "dickheads", "dickish", "dick-ish", "dickripper", "dicksipper",
                           "dickweed", "dickwhipper", "dickzipper", "diddle", "dike", "dildo", "dildos", "diligaf",
                           "dillweed", "dimwit", "dingle", "dipship", "doggie-style", "doggy-style", "dong", "doofus",
                           "doosh", "dopey", "douch3", "douche", "douchebag", "douchebags", "douchey", "drunk",
                           "dumass", "dumbass", "dumbasses", "dummy", "dyke", "dykes", "ejaculate", "enlargement",
                           "erect", "erection", "erotic", "essohbee", "extacy", "extasy", "f.u.c.k", "fack", "fag",
                           "fagg", "fagged", "faggit", "faggot", "fagot", "fags", "faig", "faigt", "fannybandit",
                           "fart", "fartknocker", "fat", "felch", "felcher", "felching", "fellate", "fellatio",
                           "feltch", "feltcher", "fisted", "fisting", "fisty", "floozy", "foad", "fondle", "foobar",
                           "foreskin", "freex", "frigg", "frigga", "fubar", "fuck", "f-u-c-k", "fuckass", "fucked",
                           "fucked", "fucker", "fuckface", "fuckin", "fucking", "fucknugget", "fucknut", "fuckoff",
                           "fucks", "fucktard", "fuck-tard", "fuckup", "fuckwad", "fuckwit", "fudgepacker", "fuk",
                           "fvck", "fxck", "gae", "gai", "ganja", "gay", "gays", "gey", "gfy", "ghay", "ghey", "gigolo",
                           "glans", "goatse", "godamn", "godamnit", "goddam", "goddammit", "goddamn", "goldenshower",
                           "gonad", "gonads", "gook", "gooks", "gringo", "gspot", "g-spot", "gtfo", "guido", "h0m0",
                           "h0mo", "handjob", "he11", "hebe", "heeb", "hell", "hemp", "heroin", "herp", "herpes",
                           "herpy", "hitler", "hiv", "hobag", "hom0", "homey", "homo", "homoey", "honky", "hooch",
                           "hookah", "hooker", "hoor", "hootch", "hooter", "hooters", "horny", "hump", "humped",
                           "humping", "hussy", "hymen", "inbred", "incest", "injun", "j3rk0ff", "jackass", "jackhole",
                           "jackoff", "jap", "japs", "jerk", "jerk0ff", "jerked", "jerkoff", "jism", "jiz", "jizm",
                           "jizz", "jizzed", "junkie", "junky", "kike", "kikes", "kill", "kinky", "kkk", "klan",
                           "knobend", "kooch", "kooches", "kootch", "kraut", "kyke", "labia", "lech", "leper",
                           "lesbians", "lesbo", "lesbos", "lez", "lezbian", "lezbians", "lezbo", "lezbos", "lezzie",
                           "lezzies", "lezzy", "lmao", "lmfao", "loin", "loins", "lube", "lusty", "mams", "massa",
                           "masterbate", "masterbating", "masterbation",
                           "masturbate", "masturbating", "masturbation", "maxi", "menses", "menstruate", "menstruation",
                           "meth", "m-fucking", "mofo", "molest", "moolie", "moron", "motherfucka", "motherfucker",
                           "motherfucking", "mtherfucker", "mthrfucker", "mthrfucking", "muff", "muffdiver", "murder",
                           "muthafuckaz", "muthafucker", "mutherfucker", "mutherfucking", "muthrfucking", "nad", "nads",
                           "naked", "napalm", "nappy", "nazi", "nazism", "negro", "nigga", "niggah", "niggas", "niggaz",
                           "nigger", "nigger", "niggers", "niggle", "niglet", "nimrod", "ninny", "nipple", "nooky",
                           "nympho", "opiate", "opium", "oral", "orally", "organ", "orgasm", "orgasmic", "orgies",
                           "orgy", "ovary", "ovum", "ovums", "p.u.s.s.y.", "paddy", "paki", "pantie", "panties",
                           "panty", "pastie", "pasty", "pcp", "pecker", "pedo", "pedophile", "pedophilia",
                           "pedophiliac", "pee", "peepee", "penetrate", "penetration", "penial", "penile", "penis",
                           "perversion", "peyote", "phalli", "phallic", "phuck", "pillowbiter", "pimp", "pinko", "piss",
                           "pissed", "pissoff", "piss-off", "pms", "polack", "pollock", "poon", "poontang", "porn",
                           "porno", "pornography", "pot", "potty", "prick", "prig", "prostitute", "prude", "pube",
                           "pubic", "pubis", "punkass", "punky", "puss", "pussies", "pussy", "pussypounder", "puto",
                           "queaf", "queef", "queef", "queer", "queero", "queers", "quicky", "quim", "racy", "rape",
                           "raped", "raper", "rapist", "raunch", "rectal", "rectum", "rectus", "reefer", "reetard",
                           "reich", "retard", "retarded", "revue", "rimjob", "ritard", "rtard", "r-tard", "rum", "rump",
                           "rumprammer", "ruski", "s.h.i.t.", "s.o.b.", "s0b", "sadism", "sadist", "scag", "scantily",
                           "schizo", "schlong", "screw", "screwed", "scrog", "scrot", "scrote", "scrotum", "scrud",
                           "scum", "seaman", "seamen", "seduce", "semen", "sex", "sexual", "sh1t", "s-h-1-t",
                           "shamedame", "shit", "s-h-i-t", "shite", "shiteater", "shitface", "shithead", "shithole",
                           "shithouse", "shits", "shitt", "shitted", "shitter", "shitty", "shiz", "sissy", "skag",
                           "skank", "slave", "sleaze", "sleazy", "slut", "slutdumper", "slutkiss", "sluts", "smegma",
                           "smut", "smutty", "snatch", "sniper", "snuff", "s-o-b", "sodom", "souse", "soused", "sperm",
                           "spic", "spick", "spik", "spiks", "spooge", "spunk", "steamy", "stfu", "stiffy", "stoned",
                           "strip", "stroke", "stupid", "suck", "sucked", "sucking", "sumofabiatch", "t1t", "tampon",
                           "tard", "tawdry", "teabagging", "teat", "terd", "teste", "testee", "testes", "testicle",
                           "testis", "thrust", "thug", "tinkle", "tit", "titfuck", "titi", "tits", "tittiefucker",
                           "titties", "titty", "tittyfuck", "tittyfucker", "toke", "toots", "tramp", "transsexual",
                           "trashy", "tubgirl", "turd", "tush", "twat", "twats", "ugly", "undies", "unwed", "urinal",
                           "urine", "uterus", "uzi", "vag", "vagina", "valium", "viagra", "virgin", "vixen", "vodka",
                           "vomit", "voyeur", "vulgar", "vulva", "wad", "wang", "wank", "wanker", "wazoo", "wedgie",
                           "weed", "weenie", "weewee", "weiner", "weirdo", "wench", "wetback", "wh0re", "wh0reface",
                           "whitey", "whiz", "whoralicious", "whore", "whorealicious", "whored", "whoreface",
                           "whorehopper", "whorehouse", "whores", "whoring", "wigger", "womb", "woody", "wop", "wtf",
                           "x-rated", "xxx", "yeasty", "yobbo", "zoophile"}

    # Convert each element to lowercase
    NamesDataSet = {name.lower() for name in NamesDataSet}
    #Preform Union
    Names = NamesDataSet | MyNames

    # Convert each element to lowercase
    Curse_words_DataSet = {word.lower() for word in Curse_words_DataSet}
    # Preform Union
    CURSE_WORDS = Curse_words_DataSet | My_CURSE_WORDS

    @staticmethod
    def preprocess_lyrics(lyrics):
        """
        Removes text inside brackets from the lyrics.
        """
        return re.sub(r'\[.*?]', '', lyrics).strip()

    @staticmethod
    def load_lyrics_from_file(file_path):
        """
        Loads lyrics from a single CSV file and preprocesses them to remove text inside brackets.
        Assumes each CSV file has columns 'Song Title', 'Lyrics', and 'Album'.
        """
        df = pd.read_csv(file_path, encoding='utf-8-sig')
        df['Lyrics'] = df['Lyrics'].apply(Helper.preprocess_lyrics)
        return df

    Singles = [
        "Demon Inside",
        "Till Hell Freezes Over",
        "Any Man",
        "Bad Influence",
        "Our House",
        "Fuck You",
        "Quitter",
        "I Remember",
        "8 Mile",
        "Bump Heads",
        "Wanksta",
        "Nail In The Coffin",
        "The Sauce",
        "Hail Mary",
        "Foolish Pride"
    ]

    SoulIntent = [
        "Fattest Skinny Kid Alive",
        "Steppin’ On To The Scene",
        "Don’t Chew With Your Mouth Full",
        "Unreallistically Graphic"
    ]

    BadMeetsEvil = [
        "Nuttin’ To Do",
        "Scary Movies"
    ]

    D12 = [
        "Chance to Advance",
        "Desperados",
        "Filthy"
    ]

    SlimShadyEP = [
        "Murder, Murder",
        "If I Had",
        "Low Down, Dirty",
        "Just the Two of Us",
        "No One’s Iller"
    ]

    Infinite = [
        "Infinite",
        "It’s O.K.",
        "Tonite",
        "313",
        "Maxine",
        "Open Mic",
        "Never 2 Far",
        "Searchin",
        "Backstabber",
        "Jealousy Woes II"
    ]

    theSlimShadyLP = [
        "My Name Is",
        "Guilty Conscience",
        "Brain Damage",
        "If I Had",
        "'97 Bonnie & Clyde",
        "Role Model",
        "My Fault",
        "Cum on Everybody",
        "Rock Bottom",
        "Just Don’t Give a Fuck",
        "As the World Turns",
        "I’m Shady",
        "Bad Meets Evil",
        "Still Don’t Give a Fuck"
    ]

    TheMarshallMathersLP = [
        "Kill You",
        "Stan",
        "Who Knew",
        "The Way I Am",
        "The Real Slim Shady",
        "Remember Me?",
        "I’m Back",
        "Marshall Mathers",
        "Drug Ballad",
        "Amityville",
        "Bitch Please II",
        "Kim",
        "Under the Influence",
        "Criminal",
        "The Kids"
    ]

    TheEminemShow = [
        "White America",
        "Business",
        "Cleanin' Out My Closet",
        "Square Dance",
        "Soldier",
        "Say Goodbye Hollywood",
        "Drips",
        "Without Me",
        "Sing for the Moment",
        "Superman",
        "Hailie's Song",
        "When the Music Stops",
        "Say What You Say",
        "Till I Collapse",
        "My Dad's Gone Crazy"
    ]

    Encore = [
        "Evil Deeds",
        "Never Enough",
        "Yellow Brick Road",
        "Like Toy Soldiers",
        "Mosh",
        "Puke",
        "My 1st Single",
        "Rain Man",
        "Big Weenie",
        "Just Lose It",
        "Ass Like That",
        "Spend Some Time",
        "Mockingbird",
        "Crazy in Love",
        "One Shot 2 Shot",
        "Encore / Curtains Down",
        "We As Americans",
        "Love You More",
        "Ricky Ticky Toc"
    ]

    Relapse = [
        "3 a.m.",
        "My Mom",
        "Insane",
        "Bagpipes From Baghdad",
        "Hello",
        "Same Song & Dance",
        "We Made You",
        "Medicine Ball",
        "Stay Wide Awake",
        "Old Time's Sake",
        "Must Be the Ganja",
        "Déjà Vu",
        "Beautiful",
        "Crack a Bottle",
        "Underground",
        "My Darling",
        "Careful What You Wish For"
    ]

    Recovery = [
        "Cold Wind Blows",
        "Talkin' 2 Myself",
        "On Fire",
        "Won't Back Down",
        "W.T.P.",
        "Going Through Changes",
        "Not Afraid",
        "Seduction",
        "No Love",
        "Space Bound",
        "Cinderella Man",
        "25 to Life",
        "So Bad",
        "Almost Famous",
        "Love the Way You Lie",
        "You're Never Over",
        "Untitled",
        "Ridaz",
        "Session One"
    ]

    TheMarshallMathersLP2 = [
        "Bad Guy",
        "Rhyme or Reason",
        "So Much Better",
        "Survival",
        "Legacy",
        "Asshole",
        "Berzerk",
        "Rap God",
        "Brainless",
        "Stronger Than I Was",
        "The Monster",
        "So Far...",
        "Love Game",
        "Headlights",
        "Evil Twin"
    ]

    Revival = [
        "Walk on Water",
        "Believe",
        "Chloraseptic",
        "Untouchable",
        "River",
        "Remind Me",
        "Like Home",
        "Bad Husband",
        "Tragic Endings",
        "Framed",
        "Nowhere Fast",
        "Heat",
        "Offended",
        "Need Me",
        "In Your Head",
        "Castle",
        "Arose"
    ]

    Kamikaze = [
        "The Ringer",
        "Greatest",
        "Lucky You",
        "Normal",
        "Stepping Stone",
        "Not Alike",
        "Kamikaze",
        "Fall",
        "Nice Guy",
        "Good Guy",
        "Venom"
    ]

    MusicToBeMurderedBy = [
        "Black Magic",
        "Alfred’s Theme",
        "Tone Deaf",
        "Book of Rhymes",
        "Favorite Bitch",
        "Guns Blazing",
        "Gnat",
        "Higher",
        "These Demons",
        "She Loves Me",
        "Killer",
        "Zeus",
        "Discombobulated",
        "Premonition",
        "Unaccommodating",
        "You Gon' Learn",
        "Those Kinda Nights",
        "In Too Deep",
        "Godzilla",
        "Darkness",
        "Leaving Heaven",
        "Yah Yah",
        "Stepdad",
        "Marsh",
        "Never Love Again",
        "Little Engine",
        "Lock It Up",
        "Farewell",
        "No Regrets",
        "I Will"
    ]

    TheDeathOfSlimShady = [
        "Renaissance",
        "Habits",
        "Brand New Dance",
        "Evil",
        "Lucifer",
        "Antichrist",
        "Fuel",
        "Road Rage",
        "Houdini",
        "Guilty Conscience 2",
        "Head Honcho",
        "Temporary",
        "Bad One",
        "Tobey",
        "Somebody Save Me"
    ]

    StraightFromTheLab = [
        "Monkey See, Monkey Do",
        "We As Americans",
        "Love You More",
        "Can I Bitch",
        "Bully",
        "6 in the Morning by D12",
        "Doe Rae Me",
        "The Kids",
        "Stimulate",
        "Rabbit Run",
        "The Conspiracy Freestyle",
        "Bump Heads",
        "God Is Cleaning Out My Closet"
    ]

    firstPeriodAlbums = [Infinite, theSlimShadyLP, TheMarshallMathersLP, TheEminemShow, StraightFromTheLab, Encore,
                         Singles, SoulIntent, BadMeetsEvil, D12, SlimShadyEP]

    firstAlbumNames = ["Infinite", "The Slim Shady LP", "The Marshall Mathers LP", "The Eminem Show",
                       "Straight From The Lab", "Encore", "Singles", "Soul Intent", "Bad Meets Evil", "D12",
                       "Slim Shady EP"]

    secondPeriodAlbums = [Relapse, Recovery, TheMarshallMathersLP2, Revival, Kamikaze, MusicToBeMurderedBy,
                          TheDeathOfSlimShady]

    secondAlbumNames = ["Relapse", "Recovery", "The Marshall Mathers LP 2", "Revival", "Kamikaze",
                        "Music To Be Murdered By", "The Death Of Slim Shady"]

    songs_first_period = set(Singles + SoulIntent + BadMeetsEvil + D12 + SlimShadyEP + Infinite + theSlimShadyLP +
                             TheMarshallMathersLP + TheEminemShow + Encore + StraightFromTheLab)

    songs_second_period = set(Relapse + Recovery + TheMarshallMathersLP2 +
                              Revival + Kamikaze + MusicToBeMurderedBy + TheDeathOfSlimShady)

    songs_names = songs_first_period | songs_second_period  # the | operator works here for union

    albums_names = set(firstAlbumNames + secondAlbumNames)

    # CSVAnalyzer
    analysis_file_paths = ['./results/song_analysis_first_period.csv', './results/song_analysis_second_period.csv']
    summary_filenames_by_album = ['./results/album_summary_first_period.csv', './results/album_summary_second_period.csv']
    summary_filenames_by_period = ['./results/first_period_summary.csv', './results/second_period_summary.csv']
